// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Output struct {
	ID string `json:"id"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type TodoCreateInput struct {
	Text string `json:"text"`
}

type TodoUpdateTextInput struct {
	Text string `json:"text"`
}
